//
//  MNKPDFContstants.h
//  MNKPDFEditor
//
//  Created by Андрей Рычков on 11.11.15.
//  Copyright © 2015 Ninenone. All rights reserved.
//

#ifndef MNKPDFContstants_h
#define MNKPDFContstants_h

#import <Foundation/Foundation.h>
#import <QuartzCore/QuartzCore.h>

FOUNDATION_EXPORT const CGFloat MAXIMUM_SCALE;
FOUNDATION_EXPORT const CGFloat SCALE_FACTOR;

FOUNDATION_EXPORT const size_t LEVELS_OF_DETAIL;
FOUNDATION_EXPORT const CGSize DEFAULT_TILE_SIZE;

FOUNDATION_EXPORT const CGFloat MAIN_TOOLBAR_HEIGHT;

FOUNDATION_EXPORT const CGFloat PAGEBAR_HEIGHT;
FOUNDATION_EXPORT const CGFloat PAGE_NUMBER_SPACE;
FOUNDATION_EXPORT const CGFloat PAGE_NUMBER_WIDTH;
FOUNDATION_EXPORT const CGFloat PAGE_NUMBER_HEIGHT;

FOUNDATION_EXPORT const CGFloat THUMB_SMALL_GAP;
FOUNDATION_EXPORT const CGFloat THUMB_SMALL_WIDTH;
FOUNDATION_EXPORT const CGFloat THUMB_SMALL_HEIGHT;

FOUNDATION_EXPORT const CGFloat THUMB_LARGE_WIDTH;
FOUNDATION_EXPORT const CGFloat THUMB_LARGE_HEIGHT;

FOUNDATION_EXPORT const CGFloat DRAWING_TOOLBAR_HEIGHT;
FOUNDATION_EXPORT const CGFloat DRAWING_TOOLBAR_WIDTH;

FOUNDATION_EXPORT const CGFloat DEFAULT_SPACING;

FOUNDATION_EXPORT const CGSize DEFAULT_BUTTON_SIZE;
FOUNDATION_EXPORT const CGFloat TEXT_BUTTON_PADDING;
FOUNDATION_EXPORT const CGFloat STATUS_BAR_HEIGHT;

FOUNDATION_EXPORT const size_t THUMBS_IN_ROW_PORTRAIT;
FOUNDATION_EXPORT const size_t THUMBS_IN_ROW_LANDSCAPE;

FOUNDATION_EXPORT const CGFloat LINE_WIDTH;
FOUNDATION_EXPORT const CGFloat LINE_ALPHA;
#define LINE_COLOR [UIColor blackColor]

FOUNDATION_EXPORT const CGFloat PALETTE_WIDTH;
FOUNDATION_EXPORT const CGFloat PALETTE_HEIGHT;

FOUNDATION_EXPORT const CGFloat MINIMUM_LINE_WIDTH;
FOUNDATION_EXPORT const CGFloat MAXIMUM_LINE_WIDTH;
FOUNDATION_EXPORT const CGSize PALETTE_BUTTON_SIZE;

float degreesToRadians(float degrees);
float radiansToDegrees(float radians);

#endif /* MNKPDFContstants_h */
